include = [".taplo.toml", "Cargo.toml", "crates/**/*.toml", "tools/**/*.toml"]

[formatting]
align_comments       = true
align_entries        = true
allowed_blank_lines  = 2
array_auto_collapse  = false
array_auto_expand    = true
array_trailing_comma = true
indent_string        = "    "
indent_tables        = true
reorder_keys         = true
