[workspace]
members = [
    "rist-rs-bits",
    "rist-rs-buffers", 
    "rist-rs-core", 
    "rist-rs-rtp", 
    "rist-rs-net", 
    "rist-rs-sdp",
    "rist-rs-macros",
    "rist-rs-dev-tools/rist-rs-dev-net-sim"
]
