[workspace]
members = [
    "crates/rist-rs-bits",
    "crates/rist-rs-buffers", 
    "crates/rist-rs-core", 
    "crates/rist-rs-rtp", 
    "crates/rist-rs-net", 
    "crates/rist-rs-sdp",
    "crates/rist-rs-macros",
    "tools/netzwerker"
]
