[proc.rx_1]
type = "rx"
bind = { addr = "127.0.0.1", port = 9939 }

[proc.delay]
type = "delay"
inputs = [ "rx_1" ]
delay = 5000

[proc.tx_1]
type = "tx"
inputs = [ "delay" ]
send = { address = "127.0.0.1", port = 9999 }
