[package]
edition = "2021"
name    = "rist-rs-bits"
version = "0.0.1"

[dependencies]
log           = "0.3"
rist-rs-types = { path = "../rist-rs-types" }

[features]
alloc         = []
allocator_api = []
default       = ["alloc", "std", "allocator_api"]
std           = ["rist-rs-types/std"]
